"""Shared conversation builders for the backend test suite.

This module is the deduplicated home for the ad-hoc ``_conv()`` /
``_write_conv()`` / ``_user()`` / ``_assistant()`` / ``_write_jsonl()``
helpers that 14+ files under ``backend/tests/`` used to redefine
inline. It is the home base for task C4 in
``PLANS/2026.05.18-test-hardening.md``.

Where this file lives — and why
-------------------------------

It lives at ``backend/tests/builders.py``, NOT
``backend/tests/fixtures/builders.py``. The ``fixtures/`` directory is
reserved for STATIC JSON/JSONL e2e payloads that the Playwright suite
loads off disk and that are auto-generated by
``scripts/generate_e2e_fixtures.py`` (see ``fixtures/README.md``: "Do
not edit by hand"). Mixing a Python module in there would dilute that
"static data only" convention. The LLM council reviewed this and was
unanimous on the placement.

Migration guide for the remaining ad-hoc helpers
------------------------------------------------

If your test file currently has::

    def _conv(uuid, name, *, body, source="CLAUDE_AI", project_path=None):
        return {...}

    def _write_conv(by_org, conv):
        ...

replace BOTH definitions with::

    from backend.tests import builders as B

Then in the test body::

    conv = B.build_desktop_conv(uuid="...", name="...", body="...")
    B.write_desktop_conv(by_org, conv)

For Claude Code JSONL tests::

    from backend.tests import builders as B

    entries = [
        B.build_cc_user_entry(uuid="u1", text="hi", session_id="sess"),
        B.build_cc_assistant_entry(uuid="a1", msg_id="msg_a1", text="hi"),
    ]
    B.write_cc_jsonl(jsonl_path, entries)

NEEDLE tokens
-------------

The ``NEEDLE_*`` constants below are the canonical search-needle
strings used across multiple test files. Prefer importing the
constant over hard-coding the string so a future rename only touches
this file. They are also the DEFAULT body text for
``build_desktop_conv`` and ``build_cc_user_entry`` — callers who
don't care which token is in the body get a grep-able default for
free.

Parallel safety (pytest-xdist)
------------------------------

All builders are pure functions. Every call returns a fresh dict (no
shared module-level blueprints, no mutable default args). Callers
pass ``tmp_path`` explicitly when writing to disk, so there is no
global file-system state to race over. Safe under ``-n auto``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# NEEDLE tokens
# ---------------------------------------------------------------------------

# Existing Playwright e2e tokens, kept in sync with
# ``backend/tests/fixtures/README.md`` (the static-data side).
NEEDLE_HANDSHAKE = "NEEDLE_HANDSHAKE"
NEEDLE_BRANCH = "NEEDLE_BRANCH"
NEEDLE_TOOL = "NEEDLE_TOOL"
NEEDLE_CC = "NEEDLE_CC"

# Benchmark-suite token (preserved from
# ``backend/tests/test_search_index_benchmark.py``).
NEEDLE_BENCHMARK = "NEEDLE_BENCHMARK_TOKEN"


# ---------------------------------------------------------------------------
# Default constants
# ---------------------------------------------------------------------------

# Pinning the timestamps prevents non-determinism in any test that
# sorts by ``created_at`` / ``updated_at``. Callers that need a
# different value pass it explicitly.
_DEFAULT_CONV_CREATED_AT = "2026-05-01T12:00:00Z"
_DEFAULT_CONV_UPDATED_AT = "2026-05-01T13:00:00Z"
_DEFAULT_MSG_CREATED_AT = "2026-05-01T12:00:00Z"
_DEFAULT_MODEL = "claude-sonnet-4-6"


# ---------------------------------------------------------------------------
# Desktop conversation builders
# ---------------------------------------------------------------------------


def build_message(
    *,
    uuid: str,
    text: str,
    sender: str = "human",
    created_at: str = _DEFAULT_MSG_CREATED_AT,
    parent_message_uuid: str | None = None,
) -> dict[str, Any]:
    """One Desktop-shape chat message dict.

    Mirrors the on-disk shape that ``backend/store.py`` and the Pydantic
    ``Message`` model expect: ``uuid``, ``sender``, ``text``, ``content``
    (``[{"type": "text", "text": ...}]``), ``created_at``, ``updated_at``,
    ``parent_message_uuid``.
    """
    return {
        "uuid": uuid,
        "sender": sender,
        "text": text,
        "content": [{"type": "text", "text": text}],
        "created_at": created_at,
        "updated_at": created_at,
        "parent_message_uuid": parent_message_uuid,
    }


def build_desktop_conv(
    *,
    uuid: str,
    name: str,
    body: str | None = None,
    messages: list[dict[str, Any]] | None = None,
    source: str = "CLAUDE_AI",
    project_path: str | None = None,
    summary: str = "",
    model: str = _DEFAULT_MODEL,
    created_at: str = _DEFAULT_CONV_CREATED_AT,
    updated_at: str = _DEFAULT_CONV_UPDATED_AT,
    is_starred: bool = False,
) -> dict[str, Any]:
    """A Claude-Desktop-shaped conversation dict.

    Two ways to populate messages:

    * ``body="..."`` — convenience for the very common single-message
      case. Builds a one-message conversation with a human-sender
      message whose ``text`` is ``body``. Message UUID is
      ``f"{uuid}-m1"``.
    * ``messages=[...]`` — explicit list of message dicts (use
      :func:`build_message` to construct them). For multi-message
      scenarios.

    Exactly one of the two must be supplied. Passing both raises
    ``ValueError`` — we'd silently drop one otherwise, which has bitten
    test authors before.

    ``current_leaf_message_uuid`` is auto-computed as the last
    message's UUID.
    """
    if body is not None and messages is not None:
        raise ValueError(
            "build_desktop_conv: pass either body=... OR messages=..., not both"
        )

    if messages is None:
        # body=None defaults to NEEDLE_HANDSHAKE so an unannotated call
        # still produces a grep-able fixture body. Most test files want
        # to set body= explicitly so this is mostly a safety net.
        effective_body = body if body is not None else NEEDLE_HANDSHAKE
        msgs: list[dict[str, Any]] = [
            build_message(uuid=f"{uuid}-m1", text=effective_body),
        ]
    else:
        # Defensive copy so callers mutating the returned conv don't
        # alias back into their list.
        msgs = [dict(m) for m in messages]

    leaf_uuid = msgs[-1]["uuid"] if msgs else ""

    return {
        "uuid": uuid,
        "name": name,
        "summary": summary,
        "model": model,
        "created_at": created_at,
        "updated_at": updated_at,
        "is_starred": is_starred,
        "current_leaf_message_uuid": leaf_uuid,
        "project_path": project_path,
        "source": source,
        "chat_messages": msgs,
    }


def write_desktop_conv(by_org: Path, conv: dict[str, Any]) -> Path:
    """Persist a Desktop conversation dict to ``<by_org>/<uuid>.json``.

    Creates ``by_org`` (and any missing parents) so callers can pass
    an arbitrarily deep directory without ``mkdir`` boilerplate.
    Returns the written path.
    """
    by_org.mkdir(parents=True, exist_ok=True)
    path = by_org / f"{conv['uuid']}.json"
    path.write_text(json.dumps(conv))
    return path


# ---------------------------------------------------------------------------
# Claude Code JSONL builders
# ---------------------------------------------------------------------------


def build_cc_user_entry(
    *,
    uuid: str,
    text: str,
    session_id: str = "sess",
    cwd: str = "/tmp/p",
    git_branch: str = "main",
    timestamp: str = _DEFAULT_MSG_CREATED_AT,
    parent_uuid: str | None = None,
) -> dict[str, Any]:
    """One ``type=user`` row in Claude Code's JSONL wire format.

    Matches the shape that ``backend.claude_code_reader`` parses:
    ``type``, ``uuid``, ``sessionId``, ``cwd``, ``gitBranch``,
    ``timestamp``, ``parentUuid``, ``message: {role, content}``.
    """
    return {
        "type": "user",
        "uuid": uuid,
        "parentUuid": parent_uuid,
        "sessionId": session_id,
        "cwd": cwd,
        "gitBranch": git_branch,
        "timestamp": timestamp,
        "message": {"role": "user", "content": text},
    }


def build_cc_assistant_entry(
    *,
    uuid: str,
    msg_id: str,
    text: str,
    session_id: str = "sess",
    timestamp: str = _DEFAULT_MSG_CREATED_AT,
    parent_uuid: str | None = None,
    content: list[dict[str, Any]] | None = None,
    model: str = _DEFAULT_MODEL,
) -> dict[str, Any]:
    """One ``type=assistant`` row in Claude Code's JSONL wire format.

    ``content`` lets callers pass tool-use / tool-result blocks
    explicitly. When omitted, defaults to a single ``text`` block
    holding ``text``.
    """
    effective_content = (
        [dict(c) for c in content]
        if content is not None
        else [{"type": "text", "text": text}]
    )
    return {
        "type": "assistant",
        "uuid": uuid,
        "parentUuid": parent_uuid,
        "sessionId": session_id,
        "timestamp": timestamp,
        "message": {
            "id": msg_id,
            "role": "assistant",
            "model": model,
            "content": effective_content,
        },
    }


def write_cc_jsonl(path: Path, entries: list[dict[str, Any]]) -> Path:
    """Persist a Claude Code JSONL session at ``path``.

    Each entry becomes one line. Creates parent dirs. Returns the
    written path.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for entry in entries:
            f.write(json.dumps(entry) + "\n")
    return path
