"""V1 polish (2026-05-12): collapse `<local-command-caveat>`/<command-name>/
`<local-command-stdout>` triplets that Claude Code emits around slash commands.

User-visible regression: opening a CC session whose first conversational turns
were just `/exit` showed three raw-XML "messages" at the top of the stream
before any real content. We fold those into a single muted `"Session: /foo"`
marker so the user sees the real conversation immediately.

The collapse lives in
:func:`backend.claude_code_reader._collapse_local_command_triplets` and is
called at the end of :func:`read_claude_code_conversation` after streaming
chunks are merged. These tests pin the contract bidirectionally:

  * **Positive direction** — a triplet followed by a real user prompt must
    collapse to ``[marker, real_user, ...]`` (NOT ``[caveat, command, stdout,
    real_user, ...]``).
  * **Negative direction** — a real user message that just *mentions* the
    caveat-text outside the XML wrapper must NOT be collapsed.
  * **Orphan / phantom** — a session that contains nothing but boilerplate
    must still render *something* (the marker), so the view is never blank
    and the phantom-carve-out invariant
    (``test_phantom_caveat_carveout.py:140``: ``len(chat_messages) >= 2``
    when paired with a real message) is preserved.
  * **/compact passthrough** — the existing compact-markers system owns
    ``/compact`` triplets; this collapser must leave them alone.
"""

from __future__ import annotations

import json
from pathlib import Path

from backend.claude_code_reader import read_claude_code_conversation


_CAVEAT_TEXT = (
    "<local-command-caveat>Caveat: The messages below were generated by the "
    "user while running local commands. DO NOT respond to these messages or "
    "otherwise consider them in your response unless the user explicitly "
    "asks you to.</local-command-caveat>"
)


def _write_jsonl(path: Path, entries: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for entry in entries:
            f.write(json.dumps(entry) + "\n")


def _user(uuid: str, text: str, *, ts: str, parent: str | None = None) -> dict:
    return {
        "type": "user",
        "uuid": uuid,
        "parentUuid": parent,
        "sessionId": "sess",
        "cwd": "/tmp/p",
        "timestamp": ts,
        "message": {"role": "user", "content": text},
    }


def _assistant(uuid: str, msg_id: str, text: str, *, ts: str, parent: str | None = None) -> dict:
    return {
        "type": "assistant",
        "uuid": uuid,
        "parentUuid": parent,
        "sessionId": "sess",
        "timestamp": ts,
        "message": {
            "id": msg_id,
            "role": "assistant",
            "model": "claude-sonnet-4-6",
            "content": [{"type": "text", "text": text}],
        },
    }


def test_exit_triplet_collapses_to_single_marker_then_real_message_first(tmp_path: Path) -> None:
    """The canonical bug report.

    JSONL stream is exactly what session `76fe578b-...` had at the top:
    a `<local-command-caveat>` row, a `<command-name>/exit</command-name>`
    row, a `<local-command-stdout>Goodbye!</local-command-stdout>` row,
    then the user's real first prompt. After our collapser the rendered
    stream must start with a single "Session: /exit" marker followed by
    the real prompt — NOT three raw-XML rows.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            "<command-name>/exit</command-name>\n"
            "            <command-message>exit</command-message>\n"
            "            <command-args></command-args>",
            ts="2026-04-19T01:31:14Z",
            parent="u1",
        ),
        _user(
            "u3",
            "<local-command-stdout>Goodbye!</local-command-stdout>",
            ts="2026-04-19T01:31:14Z",
            parent="u2",
        ),
        _user(
            "u4",
            "I don't think we've pushed this repo yet. Check for me.",
            ts="2026-04-19T01:53:49Z",
            parent="u3",
        ),
        _assistant(
            "a1",
            "asst_1",
            "Let me check the git remote configuration.",
            ts="2026-04-19T01:53:54Z",
            parent="u4",
        ),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    # Triplet (3 rows) + real_user + assistant = 5 rows pre-collapse, 3 post.
    assert len(messages) == 3, (
        f"expected triplet to collapse to 1 marker + real user + assistant; "
        f"got {len(messages)} messages: {[m.get('text', '')[:60] for m in messages]}"
    )

    # Marker must be at index 0.
    marker = messages[0]
    assert marker.get("is_command_marker") is True, (
        f"first message must be the synthetic command marker; got: {marker!r}"
    )
    assert marker.get("sender") == "human"
    assert marker.get("text") == "Session: /exit", (
        f"marker text should be 'Session: /exit'; got: {marker.get('text')!r}"
    )
    # Marker must NOT contain raw XML — that's the whole point of the fix.
    assert "<local-command-caveat>" not in marker.get("text", "")
    assert "<command-name>" not in marker.get("text", "")
    assert "<local-command-stdout>" not in marker.get("text", "")

    # The real user prompt must be at index 1, intact.
    real_user = messages[1]
    assert real_user.get("sender") == "human"
    assert "pushed this repo" in real_user.get("text", "")
    assert not real_user.get("is_command_marker", False)

    # Assistant follows.
    assert messages[2].get("sender") == "assistant"


def test_real_user_message_mentioning_caveat_text_is_not_collapsed(tmp_path: Path) -> None:
    """Bidirectional negative test.

    A user can legitimately PASTE the caveat string into a message
    (e.g. asking us about CC's boilerplate). Such a message does NOT
    start with ``<local-command-caveat>`` and is NOT preceded by a
    `<command-name>` row, so it must NOT be collapsed away.

    If this test fails it means the collapser is over-firing on
    content-substring matches rather than prefix matches — which would
    silently delete legitimate user messages.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user(
            "u1",
            "Hey, what does this CC line mean: 'Caveat: The messages below "
            "were generated by the user while running local commands'? Is "
            "it safe to ignore?",
            ts="2026-04-19T01:31:14Z",
        ),
        _assistant("a1", "asst_1", "It's CC boilerplate around slash commands.",
                   ts="2026-04-19T01:31:20Z", parent="u1"),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    assert len(messages) == 2, "non-boilerplate message must NOT be collapsed"
    assert not messages[0].get("is_command_marker", False), (
        "real user message that quotes the caveat text must NOT be flagged "
        "as a command marker"
    )
    assert "Caveat: The messages below" in messages[0].get("text", ""), (
        "real user message body must survive the collapser intact"
    )


def test_orphan_caveat_alone_collapses_to_generic_marker(tmp_path: Path) -> None:
    """A session that contains nothing but a single caveat row plus one
    real user message must collapse to ``[generic_marker, real_user, ...]``
    — never blank the view, never drop the real message.

    This is the phantom-adjacent case: not pure phantom (we have a real
    user turn), but the leading boilerplate stands alone without a
    `<command-name>` follower. The marker text falls back to the generic
    "Session: Local command" label.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user("u2", "Real follow-up question about something.",
              ts="2026-04-19T01:31:20Z", parent="u1"),
        _assistant("a1", "asst_1", "Sure, here's an answer.",
                   ts="2026-04-19T01:31:25Z", parent="u2"),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    assert len(messages) == 3, (
        f"expected [generic_marker, real_user, assistant]; got {len(messages)}"
    )
    assert messages[0].get("is_command_marker") is True
    # No <command-name> in the run, so the marker uses the generic label.
    assert messages[0].get("text") == "Session: Local command"
    assert "Real follow-up question" in messages[1].get("text", "")


def test_compact_triplet_is_NOT_collapsed_by_local_command_pass(tmp_path: Path) -> None:
    """The existing :func:`extract_compact_markers` system owns ``/compact``
    runs and renders them via the parallel ``compact_markers`` list (with a
    dedicated UI affordance — see ``frontend/.../CompactMarker.tsx``).

    The local-command collapser MUST leave /compact triplets alone so the
    two systems don't fight. If this test starts failing it means we're
    swallowing /compact rows that the compact-marker pipeline expects to
    find — the user would lose the "Compacted (manual)" pill and the
    user_prompt panel.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", "Initial question that fills the context window.",
              ts="2026-04-19T01:00:00Z"),
        _assistant("a1", "asst_1", "Long answer here.",
                   ts="2026-04-19T01:00:05Z", parent="u1"),
        # /compact triplet — same SHAPE as /exit but owned by another system.
        {
            "type": "user",
            "uuid": "uc1",
            "parentUuid": "a1",
            "sessionId": "sess",
            "cwd": "/tmp/p",
            "timestamp": "2026-04-19T01:01:00Z",
            "isCompactSummary": True,
            "message": {"role": "user", "content": "Summary of conversation so far..."},
        },
        _user("uc2",
              "<command-name>/compact</command-name>\n"
              "            <command-args>focus on the API design</command-args>",
              ts="2026-04-19T01:01:01Z", parent="uc1"),
        _user("u2", "Now continue with the next topic.",
              ts="2026-04-19T01:01:10Z", parent="uc2"),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    # The compact-markers pipeline must still see the /compact summary.
    compact_markers = detail["compact_markers"]
    assert len(compact_markers) == 1, (
        f"the /compact pipeline must surface 1 marker; got {len(compact_markers)} — "
        "the local-command collapser is over-firing on /compact"
    )
    assert compact_markers[0]["kind"] == "manual"
    assert compact_markers[0]["user_prompt"] == "focus on the API design"

    # No synthetic "Session: /compact" marker should leak into the message list.
    for m in messages:
        if m.get("is_command_marker"):
            assert m.get("text") != "Session: /compact", (
                "/compact must be handled by extract_compact_markers, not by "
                "the local-command collapser"
            )


def test_marker_uuid_bridges_parent_chain(tmp_path: Path) -> None:
    """When a triplet is collapsed, the synthetic marker must inherit the
    FIRST run-member's uuid so any downstream message that pointed at any
    of the dropped rows via ``parent_message_uuid`` still resolves.

    The frontend currently renders by array order (not parent chain), but
    the parent-chain invariant is part of the public message shape — exports,
    branch traversal, and the markdown bundle all rely on it. Belt-and-
    suspenders: pin it now so a future renderer can lean on it.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user("u2",
              "<command-name>/exit</command-name>\n"
              "            <command-args></command-args>",
              ts="2026-04-19T01:31:14Z", parent="u1"),
        _user("u3", "<local-command-stdout>Goodbye!</local-command-stdout>",
              ts="2026-04-19T01:31:14Z", parent="u2"),
        _user("u4", "Real prompt.", ts="2026-04-19T01:31:20Z", parent="u3"),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    # The marker should have uuid 'u1' (the first triplet member).
    assert messages[0]["uuid"] == "u1", (
        f"marker must inherit FIRST run-member's uuid for the parent-chain "
        f"bridge; got uuid={messages[0]['uuid']!r}"
    )
    # The real user message's parent_message_uuid was 'u3' (the last triplet
    # member). After collapse, that pointer is dangling — but since the
    # frontend uses array order, the dangling pointer is acceptable. What
    # MATTERS is that the marker keeps the chain "anchored" via its own
    # uuid so a future parent-chain walker doesn't lose its place.
    assert messages[1]["text"] == "Real prompt."


# ---------------------------------------------------------------------------
# Args-preservation tests (V1 polish round 3, 2026-05-12).
#
# Bug report: session `76fe578b-7872-4263-bc24-f911c7f2efcc` opened with a
# real /coding command carrying user prompt text in <command-args>:
#
#     <command-name>/coding</command-name>
#     <command-args>Double-check your plan with the LLM council.</command-args>
#
# The original collapser threw the args away, rendering an empty
# "Session: /coding" bubble at the top of the conversation — silent data
# loss of the user's actual message. The fix preserves args as the
# marker's `text` AND surfaces the command name in a separate
# `slash_command` field for a UI badge.
#
# These tests pin the contract on the four observable behaviors:
#   1. Argful marker carries args as text + slash_command field.
#   2. Argless marker keeps the "Session: /foo" label AND sets slash_command.
#   3. Orphan caveat (no command-name row) has slash_command=None.
#   4. Argful LEADING marker is NOT flagged as prelude (would hide real
#      user content behind the SessionPreludeAffordance — silent erasure).
# ---------------------------------------------------------------------------


def test_argful_command_marker_carries_args_as_text_and_slash_command(
    tmp_path: Path,
) -> None:
    """A /coding marker with non-empty <command-args> must put the args
    body into `text` and the command name into `slash_command`.

    This is the canonical bug fix: the original collapser produced
    `text="Session: /coding"` and discarded the args. Post-fix the args
    body IS the text, and the badge gets the command name via the new
    `slash_command` field.

    V1 polish (2026-05-13, Fix 2): `is_command_marker` is now FALSE on
    argful markers (spec invariant X1: argful is never a marker). The
    `text` body IS real user content; downstream consumers that filter
    on `is_command_marker` (export, prelude pass, future "skip markers"
    affordance) MUST NOT suppress argful bubbles. The badge is driven
    by `slash_command`, not by `is_command_marker`, so it still renders.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            "<command-name>/coding</command-name>\n"
            "            <command-message>coding</command-message>\n"
            "            <command-args>Double-check your plan with the "
            "LLM council.</command-args>",
            ts="2026-04-19T01:31:14Z",
            parent="u1",
        ),
        # No <local-command-stdout> row — /coding is interactive, so CC
        # routes the args straight to Claude and skips the stdout frame.
        _assistant(
            "a1",
            "asst_1",
            "Sure, let me run the council.",
            ts="2026-04-19T01:31:20Z",
            parent="u2",
        ),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    assert len(messages) == 2, (
        f"expected [marker, assistant]; got {len(messages)} messages: "
        f"{[m.get('text', '')[:60] for m in messages]}"
    )

    marker = messages[0]
    # Spec invariant X1 (V1 polish 2026-05-13): argful is never a marker.
    assert marker.get("is_command_marker") is False, (
        f"argful /coding marker must have is_command_marker=False (spec X1); "
        f"got {marker.get('is_command_marker')!r}"
    )
    assert marker.get("slash_command") == "/coding", (
        f"slash_command must carry the command name; got {marker.get('slash_command')!r}"
    )
    # The ENTIRE point of the fix: the user's prompt body is preserved
    # as the marker's text. Raw XML is gone.
    assert marker.get("text") == "Double-check your plan with the LLM council.", (
        f"marker text must be the args body verbatim (stripped); got: "
        f"{marker.get('text')!r}"
    )
    assert "<command-args>" not in marker.get("text", "")
    assert "<command-name>" not in marker.get("text", "")
    # The content list mirrors the text so MarkdownRenderer sees a
    # single text block with the args body.
    assert marker.get("content") == [
        {"type": "text", "text": "Double-check your plan with the LLM council."}
    ]


def test_argless_marker_uses_session_label_AND_sets_slash_command(
    tmp_path: Path,
) -> None:
    """An /exit marker (empty <command-args></command-args>) MUST keep
    the legacy `"Session: /exit"` label so the bubble carries SOMETHING
    visible — but MUST also set `slash_command="/exit"` so the new
    SlashCommandBadge renders on argless markers too (uniform UX: every
    marker shows the badge).

    This is the regression that pins parity: the badge appears for both
    argful AND argless markers; only the text differs.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            "<command-name>/exit</command-name>\n"
            "            <command-message>exit</command-message>\n"
            "            <command-args></command-args>",
            ts="2026-04-19T01:31:14Z",
            parent="u1",
        ),
        _user(
            "u3",
            "<local-command-stdout>Goodbye!</local-command-stdout>",
            ts="2026-04-19T01:31:14Z",
            parent="u2",
        ),
        _user(
            "u4",
            "Real follow-up.",
            ts="2026-04-19T01:31:20Z",
            parent="u3",
        ),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    marker = messages[0]
    assert marker.get("is_command_marker") is True
    assert marker.get("slash_command") == "/exit", (
        "argless markers MUST also carry slash_command so the badge "
        "renders uniformly across argful/argless cases"
    )
    assert marker.get("text") == "Session: /exit", (
        f"argless marker must keep the 'Session: /foo' label; got: {marker.get('text')!r}"
    )


def test_orphan_caveat_has_no_slash_command_field(tmp_path: Path) -> None:
    """An orphan caveat run (caveat present, NO <command-name> row) must
    produce a marker with `slash_command=None`. Otherwise the frontend's
    badge would render an empty/garbage label.

    The marker text falls back to "Session: Local command" (generic
    label) — same as the legacy behavior before args preservation.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            "Real follow-up question.",
            ts="2026-04-19T01:31:20Z",
            parent="u1",
        ),
        _assistant(
            "a1",
            "asst_1",
            "Sure.",
            ts="2026-04-19T01:31:25Z",
            parent="u2",
        ),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    marker = messages[0]
    assert marker.get("is_command_marker") is True
    assert marker.get("slash_command") is None, (
        f"orphan-caveat markers must have slash_command=None; got: "
        f"{marker.get('slash_command')!r}"
    )
    assert marker.get("text") == "Session: Local command"


def test_argful_leading_marker_is_NOT_flagged_as_prelude(tmp_path: Path) -> None:
    """When a CC session OPENS with an argful command (e.g. /coding with
    a real user prompt body), that marker MUST NOT be flagged as
    prelude — the SessionPreludeAffordance would hide it by default,
    silently burying the user's actual first message.

    This is the regression that pairs the args-preservation backend
    change with the prelude-flag change. Without this fix, session
    `76fe578b-...` would hide the user's "Double-check your plan with
    the LLM council." behind the affordance — exactly the symptom the
    user reported.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            "<command-name>/coding</command-name>\n"
            "            <command-args>Double-check your plan with the "
            "LLM council.</command-args>",
            ts="2026-04-19T01:31:14Z",
            parent="u1",
        ),
        _assistant(
            "a1",
            "asst_1",
            "Sure.",
            ts="2026-04-19T01:31:20Z",
            parent="u2",
        ),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    marker = messages[0]
    # Spec invariant X1 (V1 polish 2026-05-13, Fix 2): argful is never a
    # marker — `is_command_marker` is False here too.
    assert marker.get("is_command_marker") is False, (
        f"argful /coding marker must have is_command_marker=False (spec X1); "
        f"got {marker.get('is_command_marker')!r}"
    )
    assert marker.get("slash_command") == "/coding"
    # THE invariant: argful leading marker is NOT prelude.
    assert marker.get("is_prelude") is not True, (
        "argful leading markers MUST NOT be flagged as prelude — "
        "they carry the user's actual prompt and would be silently "
        "hidden behind the SessionPreludeAffordance"
    )
    # And the count exposed to the frontend MUST be 0 so the affordance
    # doesn't render at all.
    assert detail.get("prelude_hidden_count") == 0, (
        f"prelude_hidden_count must be 0 when the leading marker is "
        f"argful; got: {detail.get('prelude_hidden_count')!r}"
    )


def test_argless_marker_followed_by_argful_marker_only_first_is_prelude(
    tmp_path: Path,
) -> None:
    """Mixed leading run: an argless /exit triplet, followed by CC's
    canned `"No response requested."` assistant reply (which the fold
    pass absorbs into the /exit marker), followed by an argful /coding
    triplet that carries the user's REAL prompt content.

    Expected post-collapse + fold + prelude-flag:
      * `messages[0]`: /exit marker, argless, slash_command="/exit",
        `is_prelude=True`, `assistant_canned_response_consumed=True`.
      * `messages[1]`: /coding marker, argful, slash_command="/coding",
        text="Real prompt here.", `is_prelude=False` (argful → breaks
        the prelude run).
      * `prelude_hidden_count == 1` — only the /exit is hidden.

    Without the args-preservation prelude-flag guard, the /coding marker
    would be flagged as prelude too (it's still a command-marker in the
    leading position) and silently buried behind the affordance — exactly
    the regression that motivated the fix. The canned-response assistant
    between the two triplets mirrors the real `76fe578b-...` JSONL shape:
    every /exit gets a canned reply, which BREAKS the consecutive-user
    run in the collapser, so each triplet becomes its own marker.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        # First triplet: argless /exit.
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            "<command-name>/exit</command-name>\n"
            "            <command-args></command-args>",
            ts="2026-04-19T01:31:14Z",
            parent="u1",
        ),
        _user(
            "u3",
            "<local-command-stdout>Goodbye!</local-command-stdout>",
            ts="2026-04-19T01:31:14Z",
            parent="u2",
        ),
        # CC's canned reply between triplets — breaks the consecutive-
        # user run so each triplet becomes its own marker. The fold pass
        # absorbs this into the preceding marker.
        _assistant(
            "a0",
            "asst_0",
            "No response requested.",
            ts="2026-04-19T01:31:15Z",
            parent="u3",
        ),
        # Second triplet: argful /coding with REAL user content.
        _user("u4", _CAVEAT_TEXT, ts="2026-04-19T01:50:00Z", parent="a0"),
        _user(
            "u5",
            "<command-name>/coding</command-name>\n"
            "            <command-args>Real prompt here.</command-args>",
            ts="2026-04-19T01:50:00Z",
            parent="u4",
        ),
        _assistant(
            "a1",
            "asst_1",
            "Working on it.",
            ts="2026-04-19T01:50:05Z",
            parent="u5",
        ),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    # First /exit marker (argless) → prelude; canned response absorbed.
    assert messages[0].get("is_command_marker") is True, (
        f"messages[0] should be the /exit marker; got: {messages[0]!r}"
    )
    assert messages[0].get("slash_command") == "/exit"
    assert messages[0].get("is_prelude") is True
    assert messages[0].get("assistant_canned_response_consumed") is True

    # Second /coding marker (argful) → NOT prelude, text carries args.
    # Spec invariant X1 (V1 polish 2026-05-13, Fix 2): argful is never a
    # marker either, so is_command_marker must be False here too.
    assert messages[1].get("is_command_marker") is False, (
        f"argful /coding marker must have is_command_marker=False (spec X1); "
        f"got {messages[1].get('is_command_marker')!r}"
    )
    assert messages[1].get("slash_command") == "/coding"
    assert messages[1].get("is_prelude") is not True, (
        "the argful /coding marker must break the prelude run — "
        "it carries the user's real prompt content"
    )
    assert messages[1].get("text") == "Real prompt here."

    # Affordance should hide ONLY the leading argless run (1 marker).
    assert detail.get("prelude_hidden_count") == 1


def test_marker_args_with_literal_close_tag_in_body_survives_greedy_regex(
    tmp_path: Path,
) -> None:
    """Bidirectional negative test: the args regex
    `<command-args>(.*?)</command-args>(?=\\s*(?:<command-name>|$))`
    (V1 polish 2026-05-14, Bug 1 council fix) must correctly span the
    FULL args body even when the body contains the literal substring
    `</command-args>` (CC does not XML-escape user input).

    Why this still works after the 2026-05-14 regex change: the
    trailing-context lookahead requires the close tag to be followed by
    `\\s*<command-name>` or end-of-row. A literal `</command-args>` in
    the middle of the body is followed by prose (` means in CC...`),
    NOT a `<command-name>` tag — so the lookahead fails at the inner
    occurrence and the engine continues matching until the REAL wrapper
    close at end-of-row.

    Historical context: an earlier (2026-05-13) tempered-greedy
    `((?:(?!<command-name>).)*)` regex also passed this test, but
    failed on a sibling case (literal `<command-name>` substring in
    the body — Bug 1, fixed 2026-05-14). This bidirectional test was
    kept intact; the regex impl evolved.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    pathological = (
        "Explain what `</command-args>` means in CC's JSONL format. "
        "I'm debugging a parser."
    )
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            f"<command-name>/coding</command-name>\n"
            f"            <command-args>{pathological}</command-args>",
            ts="2026-04-19T01:31:14Z",
            parent="u1",
        ),
        _assistant("a1", "asst_1", "Sure.",
                   ts="2026-04-19T01:31:20Z", parent="u2"),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    marker = detail["chat_messages"][0]
    # The full pathological string is preserved (modulo .strip()).
    assert marker.get("text") == pathological, (
        f"greedy regex must capture full args body even with literal "
        f"</command-args> inside; got: {marker.get('text')!r}"
    )


def test_marker_args_with_literal_command_name_in_body_survives(
    tmp_path: Path,
) -> None:
    """V1 polish (2026-05-14, Bug 1 cross-provider council fix): the args
    extractor must tolerate a literal `<command-name>` SUBSTRING inside
    the args body.

    User-visible regression (pre-fix): a user prompt like
        /coding Explain what <command-name>/exit</command-name> means in CC's JSONL.
    triggered the tempered-greedy regex
    `<command-args>((?:(?!<command-name>).)*)</command-args>` to return
    `None` (the negative lookahead fired on the literal substring),
    which collapsed the marker text to the argless fallback
    `"Session: /coding"` — silent data loss of the user's actual prompt.

    The fix anchors the close to a real structural boundary
    (`</command-args>(?=\\s*(?:<command-name>|$))`) so the negative-
    lookahead-on-substring trap is gone. The full body — including the
    literal `<command-name>/exit</command-name>` substring — is
    preserved.

    Bidirectional pair: the sibling test
    `..._with_literal_close_tag_in_body_survives_greedy_regex` covers
    the literal `</command-args>` variant of the same class of bug.

    Empirical proof (sanity, in addition to the integration assertion
    below): the test directly imports the compiled regex and asserts the
    match succeeds, so a regex regression to a tempered-greedy variant
    is caught at the regex layer too — not only at the marker level.
    """
    # First, prove the regex itself does the right thing — independent
    # of the surrounding pipeline. If a future refactor changes the
    # regex strategy without updating this test, this assertion fires
    # before the integration test runs.
    from backend.claude_code_reader import _LOCAL_CMD_ARGS_RE
    pathological = (
        "Explain what <command-name>/exit</command-name> means in CC's "
        "JSONL. I'm debugging a parser."
    )
    row_text = (
        f"<command-name>/coding</command-name>\n"
        f"            <command-args>{pathological}</command-args>"
    )
    m = _LOCAL_CMD_ARGS_RE.search(row_text)
    assert m is not None, (
        "Bug 1 regression: the args regex returned None on a body "
        "containing a literal <command-name> substring. The fix must "
        "anchor the close on `(?=\\s*(?:<command-name>|$))` so literal "
        "substrings inside the body don't break extraction."
    )
    assert m.group(1) == pathological, (
        f"args regex must capture the full body verbatim including the "
        f"literal <command-name> substring; got: {m.group(1)!r}"
    )

    # Now the full-pipeline integration check: the marker bubble must
    # carry the full pathological prompt as its text.
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            f"<command-name>/coding</command-name>\n"
            f"            <command-args>{pathological}</command-args>",
            ts="2026-04-19T01:31:14Z",
            parent="u1",
        ),
        _assistant("a1", "asst_1", "Sure.",
                   ts="2026-04-19T01:31:20Z", parent="u2"),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    marker = detail["chat_messages"][0]
    assert marker.get("slash_command") == "/coding"
    # Argful marker (X1): is_command_marker must be False so downstream
    # prelude/export filters don't suppress the user's real prompt.
    assert marker.get("is_command_marker") is False
    # The full pathological string survives as the marker's text.
    assert marker.get("text") == pathological, (
        f"marker text must carry the user's full prompt including the "
        f"literal <command-name> substring; got: {marker.get('text')!r}"
    )

    # Bidirectional half: the same fixture with the literal removed
    # still works (proves the test isn't accidentally passing because
    # we're matching some unrelated path).
    plain = "Explain what /exit means in CC's JSONL. I'm debugging a parser."
    path2 = tmp_path / "projects" / "-tmp-p" / "sess2.jsonl"
    _write_jsonl(path2, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            f"<command-name>/coding</command-name>\n"
            f"            <command-args>{plain}</command-args>",
            ts="2026-04-19T01:31:14Z",
            parent="u1",
        ),
        _assistant("a1", "asst_1", "Sure.",
                   ts="2026-04-19T01:31:20Z", parent="u2"),
    ])
    detail2 = read_claude_code_conversation(path2)
    assert detail2 is not None
    assert detail2["chat_messages"][0].get("text") == plain


def test_marker_args_with_literal_close_tag_adjacent_to_wrapper_close(
    tmp_path: Path,
) -> None:
    """V1 polish (2026-05-14, GPT-5.2 LLM-council regression test):
    the args body may end with a literal `</command-args>` IMMEDIATELY
    before the real wrapper close, producing the adjacency shape
        `...content</command-args></command-args>`
    in the row. The args extractor must capture the body INCLUDING the
    literal close tag and terminate only at the wrapper close.

    Why this case matters: GPT-5.2 flagged this exact failure mode when
    reviewing an earlier (rejected) Option C draft that used a
    permissive `(?=\\s*(?:<|$))` lookahead. On this input the permissive
    lookahead would have terminated at the FIRST `</command-args>`
    (because the next char is `<`, satisfying the lookahead) — silently
    dropping the literal close from the captured body. The accepted
    domain-targeted lookahead `(?=\\s*(?:<command-name>|$))` correctly
    rejects that boundary (next chars are `</command-args>`, NOT
    `<command-name>`) and continues matching until the real wrapper
    close at end-of-row.

    Bidirectional verification: pin the captured body explicitly to
    `"Look at this XML: foo</command-args>"` (the inner literal close
    MUST survive in the body).
    """
    from backend.claude_code_reader import _LOCAL_CMD_ARGS_RE
    # The adjacency shape: body ends with literal `</command-args>`
    # immediately followed by the wrapper close.
    body_with_literal_close = "Look at this XML: foo</command-args>"
    row_text = (
        f"<command-name>/coding</command-name>\n"
        f"<command-args>{body_with_literal_close}</command-args>"
    )
    m = _LOCAL_CMD_ARGS_RE.search(row_text)
    assert m is not None, "adjacency-shape input must still match"
    assert m.group(1) == body_with_literal_close, (
        f"adjacency regression: the inner literal </command-args> must "
        f"survive in the captured body. A permissive `(?=\\s*(?:<|$))` "
        f"lookahead would truncate here. Got: {m.group(1)!r}"
    )


def test_marker_args_does_not_overmatch_across_concatenated_blocks(
    tmp_path: Path,
) -> None:
    """V1 polish (2026-05-13, Fix 1) — Audit invariant #2:

    The user-reported bug: in session `76fe578b-...`, some `/exit`
    markers for 2026-04-21 and 2026-04-24 rendered as
    `'</command-args>\\n<command-name>/exit</command-name>...'` — the
    greedy `<command-args>(.*)</command-args>` regex was matching from
    the FIRST `<command-args>` to the LAST `</command-args>` in a row
    containing multiple concatenated command triplets, swallowing the
    intermediate `</command-args>` + `<command-name>` boilerplate as
    "args body."

    The fix (current, 2026-05-14): non-greedy body with a
    trailing-context lookahead
    `(.*?)</command-args>(?=\\s*(?:<command-name>|$))`. Multi-block
    rows correctly truncate at the FIRST `</command-args>` whose match
    is followed by the next `<command-name>` tag (the lookahead's
    primary anchor), so the second block's XML never leaks into the
    first block's args body.

    Bidirectional check: a row containing two glued-together triplets
    must NOT produce a marker whose `text` contains the raw XML of the
    second block.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    # Two concatenated triplets in ONE row — the exact shape from the
    # 76fe578b session.
    glued = (
        "<command-name>/exit</command-name>\n<command-args></command-args>"
        "<command-name>/exit</command-name>\n<command-args></command-args>"
    )
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-21T10:00:00Z"),
        _user("u2", glued, ts="2026-04-21T10:00:00Z", parent="u1"),
        _user("u3", "Real follow-up.", ts="2026-04-21T10:00:05Z", parent="u2"),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    marker = detail["chat_messages"][0]
    text = marker.get("text", "")
    # Spec invariants X3/X4: no raw XML triplets leak into content.
    assert "<command-name>" not in text, (
        f"multi-block row must not over-match: <command-name> XML leaked "
        f"into marker text. Got: {text!r}"
    )
    assert "</command-args>" not in text, (
        f"multi-block row must not over-match: </command-args> XML leaked "
        f"into marker text. Got: {text!r}"
    )
    # Since both triplets are argless /exit, the marker collapses to
    # the canonical "Session: /exit" label.
    assert text == "Session: /exit", (
        f"argless concatenated triplets must collapse to 'Session: /exit'; "
        f"got: {text!r}"
    )
    # And the row IS treated as an argless command marker.
    assert marker.get("is_command_marker") is True
    assert marker.get("slash_command") == "/exit"


def test_argful_marker_has_is_command_marker_false_and_carries_args_as_text(
    tmp_path: Path,
) -> None:
    """V1 polish (2026-05-13, Fix 2) — Audit invariant #1:

    Spec invariant X1 (mutual exclusion): `is_command_marker=True` AND
    non-empty `slash_command_args` MUST NOT both be true. Argful slash
    commands like `/coding <prose>` carry the user's REAL prompt and
    must NEVER be flagged as markers — downstream filters (export,
    prelude, future "skip markers") would suppress them and silently
    hide user content.

    Bidirectional pair: (a) argful → is_command_marker=False;
    (b) argless → is_command_marker=True (covered by existing tests).
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            "<command-name>/plan</command-name>\n"
            "            <command-args>Outline the migration steps.</command-args>",
            ts="2026-04-19T01:31:14Z",
            parent="u1",
        ),
        _assistant("a1", "asst_1", "Sure, here's the plan.",
                   ts="2026-04-19T01:31:20Z", parent="u2"),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    marker = detail["chat_messages"][0]

    # The contract: argful → is_command_marker=False.
    assert marker.get("is_command_marker") is False, (
        "argful /plan marker MUST have is_command_marker=False (spec X1)"
    )
    # But slash_command IS set so the SlashCommandBadge renders.
    assert marker.get("slash_command") == "/plan"
    # And the user's prose IS the body.
    assert marker.get("text") == "Outline the migration steps."


def test_internal_argless_flag_does_not_leak_to_serialized_message(
    tmp_path: Path,
) -> None:
    """The private `_argless_marker` flag is internal state shared
    between `_collapse_local_command_triplets` and
    `_flag_leading_prelude_markers`. It MUST NOT leak through to the
    public Message Pydantic model — Pydantic v2's default
    `extra='ignore'` strips undeclared fields at serialization, which
    is exactly what we want here.

    The marker dict in `detail["chat_messages"]` is the raw pre-
    serialization shape (so the field IS present here), but once it
    passes through the FastAPI/Pydantic Message model on the route
    boundary it disappears. We pin the in-dict presence so the
    prelude-flag pass keeps working AND document the pattern.
    """
    from backend.models import Message

    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            "<command-name>/exit</command-name>\n"
            "            <command-args></command-args>",
            ts="2026-04-19T01:31:14Z",
            parent="u1",
        ),
        _user(
            "u3",
            "<local-command-stdout>Goodbye!</local-command-stdout>",
            ts="2026-04-19T01:31:14Z",
            parent="u2",
        ),
        _user(
            "u4",
            "Real follow-up.",
            ts="2026-04-19T01:31:20Z",
            parent="u3",
        ),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    raw_marker = detail["chat_messages"][0]

    # Raw dict from the reader: the private flag IS present.
    assert raw_marker.get("_argless_marker") is True

    # Round-trip through Pydantic: the private flag is GONE.
    msg_model = Message.model_validate(raw_marker)
    dumped = msg_model.model_dump()
    assert "_argless_marker" not in dumped, (
        "private `_argless_marker` flag must NOT leak through Pydantic "
        "serialization — it's internal state, not API surface"
    )
    # Public fields ARE present.
    assert dumped["slash_command"] == "/exit"
    assert dumped["is_command_marker"] is True
