"""V1 polish (2026-05-12, council round 2): canned-response fold + leading-prelude flag.

User-visible regression: even after `_collapse_local_command_triplets` turned each
`/exit` triplet into a single `is_command_marker: True` marker, the JSONL still
contained the orphan assistant row CC emits as its reply to /exit — an
`assistant` message whose text is literally `"No response requested."`. Result:
the top of session `76fe578b-...` rendered as

  [marker, "No response requested.", marker, "No response requested.", real_user]

which is confusing. We now (Part A) absorb each canned-response assistant into the
preceding marker, and (Part B) flag the leading run of markers with `is_prelude:
True` so the frontend can hide them behind a "Session prelude: N earlier /exit
runs (show)" affordance.

These tests pin the contract bidirectionally:

  * **Part A positive** — marker + `"No response requested."` assistant collapses
    to 1 message; the marker carries `assistant_canned_response_consumed: True`;
    the absorbed assistant is gone from `chat_messages`.
  * **Part A counter (text mismatch)** — marker + ANY other assistant text leaves
    both messages untouched. The fold is exact-string, conservative-by-design;
    if CC ever changes its canned wording the new bubble renders verbatim.
  * **Part A counter (no marker)** — assistant `"No response requested."` NOT
    preceded by a marker (e.g. preceded by a real user message) is NOT folded.
    Otherwise legitimate "No response requested." replies (rare but possible)
    would be silently erased.
  * **Part A counter (tool blocks)** — marker + assistant whose text happens to
    equal the canned string but whose content carries `tool_use` is NOT folded.
    Tool history is real data we must preserve.
  * **Part A multi-canned run** — marker + TWO consecutive canned-response
    assistants (CC glitch) absorbs both. The first non-canned successor's
    `parent_message_uuid` is remapped past both absorbed uuids.
  * **Part A parent-chain bridge** — the successor's `parent_message_uuid` is
    remapped from the absorbed assistant's uuid to the marker's uuid.
  * **Part B positive** — 2 leading markers + real user → `prelude_hidden_count=2`,
    both markers have `is_prelude: True`, real user does NOT.
  * **Part B counter (no prelude)** — session starting with a real user message
    → `prelude_hidden_count=0`, no `is_prelude` flags anywhere.
  * **Part B counter (mid-stream marker)** — a marker AFTER the first real user
    is NOT flagged. Only the LEADING run counts.
  * **Integration** — full pipeline on canonical session shape (2 × triplet +
    2 × canned-response + real user) → 1 visible non-prelude message,
    `prelude_hidden_count=2`.
"""

from __future__ import annotations

import json
from pathlib import Path

from backend.claude_code_reader import (
    _fold_canned_assistant_responses_into_marker,
    _flag_leading_prelude_markers,
    read_claude_code_conversation,
)


_CAVEAT_TEXT = (
    "<local-command-caveat>Caveat: The messages below were generated by the "
    "user while running local commands. DO NOT respond to these messages or "
    "otherwise consider them in your response unless the user explicitly "
    "asks you to.</local-command-caveat>"
)


def _write_jsonl(path: Path, entries: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for entry in entries:
            f.write(json.dumps(entry) + "\n")


def _user(uuid: str, text: str, *, ts: str, parent: str | None = None, session_id: str = "sess") -> dict:
    return {
        "type": "user",
        "uuid": uuid,
        "parentUuid": parent,
        "sessionId": session_id,
        "cwd": "/tmp/p",
        "timestamp": ts,
        "message": {"role": "user", "content": text},
    }


def _assistant(
    uuid: str,
    msg_id: str,
    text: str,
    *,
    ts: str,
    parent: str | None = None,
    content: list[dict] | None = None,
    session_id: str = "sess",
) -> dict:
    return {
        "type": "assistant",
        "uuid": uuid,
        "parentUuid": parent,
        "sessionId": session_id,
        "timestamp": ts,
        "message": {
            "id": msg_id,
            "role": "assistant",
            "model": "claude-sonnet-4-6",
            "content": content if content is not None else [{"type": "text", "text": text}],
        },
    }


# ----------------------------------------------------------------------------
# Part A — unit tests on `_fold_canned_assistant_responses_into_marker`
# ----------------------------------------------------------------------------

def _marker(uuid: str, parent: str | None = None) -> dict:
    """Build a synthetic marker matching `_collapse_local_command_triplets`'s shape."""
    return {
        "uuid": uuid,
        "sender": "human",
        "text": "Session: /exit",
        "content": [{"type": "text", "text": "Session: /exit"}],
        "created_at": "2026-04-19T01:31:14Z",
        "updated_at": "2026-04-19T01:31:14Z",
        "truncated": False,
        "parent_message_uuid": parent,
        "attachments": [],
        "files": [],
        "is_command_marker": True,
    }


def _post_msg(uuid: str, sender: str, text: str, *, parent: str | None) -> dict:
    return {
        "uuid": uuid,
        "sender": sender,
        "text": text,
        "content": [{"type": "text", "text": text}],
        "created_at": "2026-04-19T01:53:49Z",
        "updated_at": "2026-04-19T01:53:49Z",
        "truncated": False,
        "parent_message_uuid": parent,
        "attachments": [],
        "files": [],
    }


def test_fold_canned_assistant_after_marker_absorbs_and_flags() -> None:
    """Positive Part A: marker + 'No response requested.' assistant → 1 msg."""
    marker = _marker("m1", parent=None)
    canned = _post_msg("a1", "assistant", "No response requested.", parent="m1")
    real = _post_msg("u1", "human", "Real follow-up.", parent="a1")

    out = _fold_canned_assistant_responses_into_marker([marker, canned, real])

    assert len(out) == 2, f"expected [marker, real]; got {[m.get('text') for m in out]}"
    assert out[0]["uuid"] == "m1"
    assert out[0]["is_command_marker"] is True
    assert out[0]["assistant_canned_response_consumed"] is True, (
        "fold MUST set assistant_canned_response_consumed=True on the marker"
    )
    # Parent-chain bridge: real's parent_message_uuid was 'a1' (the absorbed
    # assistant); now remapped to 'm1'.
    assert out[1]["parent_message_uuid"] == "m1", (
        f"successor's parent_message_uuid must be remapped to marker uuid; "
        f"got {out[1]['parent_message_uuid']!r}"
    )
    assert out[1]["text"] == "Real follow-up."


def test_fold_does_not_fire_when_text_differs() -> None:
    """Negative Part A: assistant text other than the exact canned string is NOT folded.

    Conservative-by-design: if CC ever changes the wording (e.g. 'No response
    needed.') the new text renders verbatim — visible, fixable, no silent erasure.
    """
    marker = _marker("m1")
    other = _post_msg("a1", "assistant", "Sure, here's a thought.", parent="m1")

    out = _fold_canned_assistant_responses_into_marker([marker, other])

    assert len(out) == 2, "no fold should occur when text differs"
    assert "assistant_canned_response_consumed" not in out[0]
    assert out[1]["text"] == "Sure, here's a thought."


def test_fold_does_not_fire_when_assistant_not_preceded_by_marker() -> None:
    """Negative Part A: 'No response requested.' from a regular conversation
    (not preceded by a marker) must NOT be folded.

    A user CAN legitimately receive this exact reply in a non-prelude context
    (e.g. mid-conversation `/exit` they later cancelled). Without this guard
    we'd silently erase real assistant content.
    """
    real_user = _post_msg("u1", "human", "Hello.", parent=None)
    canned = _post_msg("a1", "assistant", "No response requested.", parent="u1")

    out = _fold_canned_assistant_responses_into_marker([real_user, canned])

    assert len(out) == 2, "canned-response not preceded by a marker must survive"
    assert out[0]["text"] == "Hello."
    assert out[1]["text"] == "No response requested."


def test_fold_does_not_fire_when_assistant_has_tool_blocks() -> None:
    """Negative Part A: assistant whose text matches canned string BUT whose
    content carries `tool_use` is NOT folded.

    Tool history is real data — even if CC weirdly emits the canned text
    alongside a real tool call, we must NOT drop it. This is the
    Gemini-3-Pro-flagged "preserve tool history" guard.
    """
    marker = _marker("m1")
    weird_assistant = {
        "uuid": "a1",
        "sender": "assistant",
        "text": "No response requested.",
        "content": [
            {"type": "text", "text": "No response requested."},
            {"type": "tool_use", "name": "Bash", "input": {"command": "ls"}},
        ],
        "created_at": "2026-04-19T01:50:00Z",
        "updated_at": "2026-04-19T01:50:00Z",
        "truncated": False,
        "parent_message_uuid": "m1",
        "attachments": [],
        "files": [],
    }

    out = _fold_canned_assistant_responses_into_marker([marker, weird_assistant])

    assert len(out) == 2, "fold must refuse when content carries tool_use blocks"
    assert "assistant_canned_response_consumed" not in out[0]


def test_fold_handles_consecutive_canned_assistants() -> None:
    """Part A run-scan: a marker followed by TWO canned-response assistants
    (CC glitch) absorbs BOTH; successor's parent_message_uuid is remapped
    past the entire run.

    This is the Gemini-2.5-Pro-flagged correctness bug in the v1 draft.
    """
    marker = _marker("m1")
    canned1 = _post_msg("a1", "assistant", "No response requested.", parent="m1")
    canned2 = _post_msg("a2", "assistant", "No response requested.", parent="a1")
    real = _post_msg("u1", "human", "Real prompt.", parent="a2")

    out = _fold_canned_assistant_responses_into_marker([marker, canned1, canned2, real])

    assert len(out) == 2, (
        f"both canned-response assistants should be absorbed; got "
        f"{[m.get('text') for m in out]}"
    )
    assert out[0]["is_command_marker"] is True
    assert out[0]["assistant_canned_response_consumed"] is True
    # successor's parent was 'a2' (the last absorbed uuid); remapped to 'm1'.
    assert out[1]["parent_message_uuid"] == "m1", (
        f"successor's parent must be remapped past the entire absorbed run; "
        f"got {out[1]['parent_message_uuid']!r}"
    )
    assert out[1]["text"] == "Real prompt."


def test_fold_does_not_remap_when_successor_parent_is_unrelated() -> None:
    """Defensive: if the successor's parent_message_uuid does NOT point at
    any absorbed uuid (e.g. it's None for a root, or points elsewhere), the
    fold MUST NOT spuriously remap it. This catches the
    Gemini-2.5-Pro-flagged `None == None` false-positive.
    """
    marker = _marker("m1")
    canned = _post_msg("a1", "assistant", "No response requested.", parent="m1")
    # Successor's parent is None — could be a downstream-inserted root.
    real = _post_msg("u1", "human", "Real prompt.", parent=None)

    out = _fold_canned_assistant_responses_into_marker([marker, canned, real])

    assert len(out) == 2
    assert out[1]["parent_message_uuid"] is None, (
        "successor with parent=None must NOT be remapped (None==None guard)"
    )


def test_fold_handles_marker_with_no_successor() -> None:
    """Defensive: marker is the LAST entry; fold MUST NOT crash and MUST NOT
    set assistant_canned_response_consumed (nothing was absorbed).
    """
    marker = _marker("m1")

    out = _fold_canned_assistant_responses_into_marker([marker])

    assert len(out) == 1
    assert out[0]["is_command_marker"] is True
    assert "assistant_canned_response_consumed" not in out[0]


def test_fold_is_pure_functional_no_input_mutation() -> None:
    """Part A's contract: input list and member dicts are NEVER mutated.

    This is the Gemini-2.5-Pro-flagged "principle of least surprise" fix.
    A caller that retains a reference to the input list must see it
    unchanged after the call.
    """
    marker = _marker("m1")
    canned = _post_msg("a1", "assistant", "No response requested.", parent="m1")
    real = _post_msg("u1", "human", "Real prompt.", parent="a1")
    input_list = [marker, canned, real]

    # Snapshot of input dict ids so we can prove no in-place mutation.
    snapshot_ids = [id(m) for m in input_list]
    snapshot_keys = [tuple(sorted(m.keys())) for m in input_list]
    snapshot_parents = [m.get("parent_message_uuid") for m in input_list]

    _ = _fold_canned_assistant_responses_into_marker(input_list)

    # Input list length and member identity preserved.
    assert len(input_list) == 3
    assert [id(m) for m in input_list] == snapshot_ids
    # Input dict keys unchanged (no `assistant_canned_response_consumed` added).
    assert [tuple(sorted(m.keys())) for m in input_list] == snapshot_keys
    # Input dict parent_message_uuid values unchanged.
    assert [m.get("parent_message_uuid") for m in input_list] == snapshot_parents


def test_fold_is_idempotent() -> None:
    """Running the fold twice yields the same result as running it once.
    The second pass finds no marker→canned-response pair (the assistant
    is gone) so it's a no-op.
    """
    marker = _marker("m1")
    canned = _post_msg("a1", "assistant", "No response requested.", parent="m1")
    real = _post_msg("u1", "human", "Real prompt.", parent="a1")

    once = _fold_canned_assistant_responses_into_marker([marker, canned, real])
    twice = _fold_canned_assistant_responses_into_marker(once)

    assert len(once) == len(twice) == 2
    assert once[0]["assistant_canned_response_consumed"] is True
    assert twice[0]["assistant_canned_response_consumed"] is True
    assert once[1]["text"] == twice[1]["text"] == "Real prompt."


# ----------------------------------------------------------------------------
# Part B — unit tests on `_flag_leading_prelude_markers`
# ----------------------------------------------------------------------------

def test_prelude_flags_leading_markers_only() -> None:
    """Positive Part B: 2 leading markers + real user → count=2, both flagged,
    real user NOT flagged.
    """
    marker1 = _marker("m1")
    marker2 = _marker("m2")
    real = _post_msg("u1", "human", "Real prompt.", parent="m2")

    out, count = _flag_leading_prelude_markers([marker1, marker2, real])

    assert count == 2
    assert out[0]["is_prelude"] is True
    assert out[1]["is_prelude"] is True
    assert out[2].get("is_prelude", False) is False, (
        "real user message must NOT be flagged as prelude"
    )


def test_prelude_zero_when_session_starts_with_real_user() -> None:
    """Negative Part B: session starts with a real user message → count=0,
    no `is_prelude` flags anywhere.
    """
    real = _post_msg("u1", "human", "First real prompt.", parent=None)
    asst = _post_msg("a1", "assistant", "Reply.", parent="u1")

    out, count = _flag_leading_prelude_markers([real, asst])

    assert count == 0
    assert all(not m.get("is_prelude", False) for m in out)


def test_prelude_does_not_flag_mid_stream_marker() -> None:
    """Negative Part B: a marker AFTER the first real user message is NOT
    flagged. Only the LEADING run is the "session prelude" — mid-conversation
    /exit triplets should render inline.
    """
    real = _post_msg("u1", "human", "First real prompt.", parent=None)
    asst = _post_msg("a1", "assistant", "Reply.", parent="u1")
    mid_marker = _marker("m1", parent="a1")
    real2 = _post_msg("u2", "human", "Second prompt.", parent="m1")

    out, count = _flag_leading_prelude_markers([real, asst, mid_marker, real2])

    assert count == 0, "no LEADING markers → count must be 0"
    # Mid-stream marker still has is_command_marker but NOT is_prelude.
    assert out[2]["is_command_marker"] is True
    assert out[2].get("is_prelude", False) is False


def test_prelude_all_markers_session() -> None:
    """Degenerate session: only markers, no real messages. All flagged.

    This is the phantom-adjacent case — paired with the existing
    phantom-carveout invariant in `test_phantom_caveat_carveout.py`, it
    ensures the view is never blank.
    """
    marker1 = _marker("m1")
    marker2 = _marker("m2")

    out, count = _flag_leading_prelude_markers([marker1, marker2])

    assert count == 2
    assert all(m["is_prelude"] is True for m in out)


def test_prelude_is_pure_functional() -> None:
    """Part B's contract: input list and member dicts are never mutated."""
    marker = _marker("m1")
    real = _post_msg("u1", "human", "Real prompt.", parent="m1")
    input_list = [marker, real]
    snapshot_keys = [tuple(sorted(m.keys())) for m in input_list]

    _ = _flag_leading_prelude_markers(input_list)

    # Input dicts must not have gained `is_prelude` keys.
    assert [tuple(sorted(m.keys())) for m in input_list] == snapshot_keys


def test_prelude_is_idempotent() -> None:
    """Running the flag pass twice yields the same result as running it once."""
    marker = _marker("m1")
    real = _post_msg("u1", "human", "Real prompt.", parent="m1")

    once, c1 = _flag_leading_prelude_markers([marker, real])
    twice, c2 = _flag_leading_prelude_markers(once)

    assert c1 == c2 == 1
    assert once[0]["is_prelude"] is True
    assert twice[0]["is_prelude"] is True


# ----------------------------------------------------------------------------
# Integration — full pipeline on canonical session shape
# ----------------------------------------------------------------------------

def test_full_pipeline_canonical_session_76fe578b_shape(tmp_path: Path) -> None:
    """Integration: full pipeline on the EXACT shape of session
    `76fe578b-7872-4263-bc24-f911c7f2efcc` rows 5..25 (2026-04-19).

    JSONL stream:
      [caveat, /exit, stdout]                       — triplet #1
      [assistant "No response requested."]          — canned #1
      [caveat, /exit, stdout]                       — triplet #2
      [assistant "No response requested."]          — canned #2
      [real_user, real_assistant]                   — actual conversation start

    After full pipeline (collapse → fold → flag-prelude):
      [marker1 (is_prelude, consumed), marker2 (is_prelude, consumed),
       real_user, real_assistant]
    `prelude_hidden_count` MUST equal 2.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z"),
        _user(
            "u2",
            "<command-name>/exit</command-name>\n"
            "            <command-message>exit</command-message>\n"
            "            <command-args></command-args>",
            ts="2026-04-19T01:31:14Z",
            parent="u1",
        ),
        _user(
            "u3",
            "<local-command-stdout>Goodbye!</local-command-stdout>",
            ts="2026-04-19T01:31:14Z",
            parent="u2",
        ),
        _assistant("a1", "asst_1", "No response requested.",
                   ts="2026-04-19T01:49:31Z", parent="u3"),
        _user("u4", _CAVEAT_TEXT, ts="2026-04-19T01:50:49Z", parent="a1"),
        _user(
            "u5",
            "<command-name>/exit</command-name>\n"
            "            <command-message>exit</command-message>\n"
            "            <command-args></command-args>",
            ts="2026-04-19T01:50:49Z",
            parent="u4",
        ),
        _user("u6", "<local-command-stdout>Goodbye!</local-command-stdout>",
              ts="2026-04-19T01:50:49Z", parent="u5"),
        _assistant("a2", "asst_2", "No response requested.",
                   ts="2026-04-19T01:53:31Z", parent="u6"),
        _user("u7", "I don't think we've pushed this repo yet. Check for me.",
              ts="2026-04-19T01:53:49Z", parent="a2"),
        _assistant("a3", "asst_3", "Let me check the git remote configuration.",
                   ts="2026-04-19T01:53:54Z", parent="u7"),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    # Triplet collapse + canned-response fold = 2 markers + real_user + real_assistant.
    assert len(messages) == 4, (
        f"expected [marker1, marker2, real_user, real_assistant]; "
        f"got {len(messages)} messages: {[m.get('text', '')[:60] for m in messages]}"
    )

    # Both leading markers are flagged as prelude AND have consumed-canned set.
    assert messages[0]["is_command_marker"] is True
    assert messages[0]["is_prelude"] is True
    assert messages[0]["assistant_canned_response_consumed"] is True
    assert messages[1]["is_command_marker"] is True
    assert messages[1]["is_prelude"] is True
    assert messages[1]["assistant_canned_response_consumed"] is True

    # Real user message is NOT flagged.
    real_user = messages[2]
    assert real_user["sender"] == "human"
    assert "pushed this repo" in real_user["text"]
    assert not real_user.get("is_prelude", False)
    assert not real_user.get("is_command_marker", False)

    # Real assistant follows.
    assert messages[3]["sender"] == "assistant"
    assert "git remote" in messages[3]["text"]

    # The top-level prelude_hidden_count must reflect the 2 hidden markers.
    assert detail["prelude_hidden_count"] == 2, (
        f"prelude_hidden_count must equal 2; got {detail['prelude_hidden_count']}"
    )


def test_full_pipeline_session_starts_with_real_user_no_prelude(tmp_path: Path) -> None:
    """Counter-integration: session starts with a real user message →
    prelude_hidden_count=0, no is_prelude flags anywhere.

    Catches a regression where the pipeline over-fires and marks the first
    message of a normal session as prelude.
    """
    path = tmp_path / "projects" / "-tmp-p" / "sess.jsonl"
    _write_jsonl(path, [
        _user("u1", "First real prompt of the session.",
              ts="2026-04-19T01:00:00Z"),
        _assistant("a1", "asst_1", "Sure, here's a thought.",
                   ts="2026-04-19T01:00:05Z", parent="u1"),
    ])

    detail = read_claude_code_conversation(path)
    assert detail is not None
    messages = detail["chat_messages"]

    assert detail["prelude_hidden_count"] == 0
    assert len(messages) == 2
    assert all(not m.get("is_prelude", False) for m in messages)
    assert all(not m.get("is_command_marker", False) for m in messages)


# ----------------------------------------------------------------------------
# Pydantic round-trip — flags must survive store.get_conversation()
# ----------------------------------------------------------------------------

def test_pydantic_round_trip_preserves_flags(tmp_path: Path, monkeypatch) -> None:
    """The CTO's WWCMM concern: Pydantic v2 default is `extra='ignore'`, so
    if `is_command_marker` / `is_prelude` / `assistant_canned_response_consumed`
    / `prelude_hidden_count` aren't declared on the model, they get silently
    stripped before reaching the frontend.

    Round-trip the canonical session through `ConversationStore.get_conversation`
    and assert the flags survive on the Pydantic models.
    """
    # Build a CC conversations directory that the store will discover.
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    # Point the store at our tmp_path-based CC directory via env var.
    cc_dir = tmp_path / "claude"
    cc_dir.mkdir()
    projects = cc_dir / "projects" / "-tmp-p"
    projects.mkdir(parents=True)
    sess_uuid = "76fe578b-7872-4263-bc24-f911c7f2efcc"
    sess_path = projects / f"{sess_uuid}.jsonl"

    _write_jsonl(sess_path, [
        _user("u1", _CAVEAT_TEXT, ts="2026-04-19T01:31:14Z", session_id=sess_uuid),
        _user("u2",
              "<command-name>/exit</command-name>\n            <command-args></command-args>",
              ts="2026-04-19T01:31:14Z", parent="u1", session_id=sess_uuid),
        _user("u3", "<local-command-stdout>Goodbye!</local-command-stdout>",
              ts="2026-04-19T01:31:14Z", parent="u2", session_id=sess_uuid),
        _assistant("a1", "asst_1", "No response requested.",
                   ts="2026-04-19T01:49:31Z", parent="u3", session_id=sess_uuid),
        _user("u4", "Real first prompt.",
              ts="2026-04-19T01:53:49Z", parent="a1", session_id=sess_uuid),
        _assistant("a2", "asst_2", "Real reply.",
                   ts="2026-04-19T01:53:54Z", parent="u4", session_id=sess_uuid),
    ])

    monkeypatch.setenv("CLAUDE_EXPLORER_DATA_DIR", str(data_dir))
    # Point the CC reader at our fake ~/.claude.
    monkeypatch.setattr("backend.claude_code_reader.DEFAULT_CLAUDE_DIR", cc_dir)
    # Bust any process-level caches the reader may use.
    from backend.cache import get_conversation_cache
    get_conversation_cache().clear()

    from backend.store import ConversationStore
    store = ConversationStore(claude_dir=cc_dir)
    detail = store.get_conversation("76fe578b-7872-4263-bc24-f911c7f2efcc")

    assert detail is not None, "store must discover the CC session"
    # The Pydantic ConversationDetail must surface prelude_hidden_count.
    assert detail.prelude_hidden_count == 1, (
        f"prelude_hidden_count must round-trip through Pydantic; got "
        f"{detail.prelude_hidden_count}"
    )
    # The marker survives with its CC-only flags intact.
    marker_msg = detail.messages[0]
    assert marker_msg.is_command_marker is True
    assert marker_msg.is_prelude is True
    assert marker_msg.assistant_canned_response_consumed is True
    # The real user message has all flags False (Desktop-compatible default).
    real_msg = detail.messages[1]
    assert real_msg.is_command_marker is False
    assert real_msg.is_prelude is False
    assert real_msg.assistant_canned_response_consumed is False
