"""M1 from PLANS/articles/part2_revision_plan.md.

The article (line 78) promises:

    "The filter hides the empty ones while still keeping sessions that
    start with a `Caveat:` preamble and then contain real conversation
    underneath; in those cases, the UI titles the session from the
    first non-system message and keeps it in the list."

The implementation distinguishes:

  PHANTOM session  = first user message starts with "Caveat:" AND
                     ZERO assistant responses.
                     Filtered out by default.

  CAVEAT-PREFIXED  = first user message starts with "Caveat:" but at
                     least one assistant response follows.
                     Kept in the list, titled from the first real
                     (non-system) user message.

The carve-out logic lives in :func:`backend.claude_code_reader.read_claude_code_conversation`'s
phantom detection branch + the ``first_real_user`` title fallback. This
test pins both halves of the contract against a synthetic JSONL.
"""

from __future__ import annotations

import json
from pathlib import Path


from backend.claude_code_reader import (
    read_claude_code_conversation,
    read_conversation_summary_fast,
)


def _write_jsonl(path: Path, entries: list[dict]) -> None:
    """Write a list of dicts as a JSONL file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for entry in entries:
            f.write(json.dumps(entry) + "\n")


def _user_entry(
    uuid: str, text: str, *, sess: str = "test-session", cwd: str = "/tmp/p", ts: str = "2026-05-11T10:00:00Z"
) -> dict:
    """A user-typed message entry in Claude Code's JSONL shape."""
    return {
        "type": "user",
        "uuid": uuid,
        "sessionId": sess,
        "cwd": cwd,
        "gitBranch": "main",
        "timestamp": ts,
        "message": {"role": "user", "content": text},
    }


def _assistant_entry(
    uuid: str, msg_id: str, text: str, *, ts: str = "2026-05-11T10:00:01Z"
) -> dict:
    """An assistant response entry in Claude Code's JSONL shape."""
    return {
        "type": "assistant",
        "uuid": uuid,
        "timestamp": ts,
        "message": {
            "id": msg_id,
            "role": "assistant",
            "model": "claude-sonnet-4-6",
            "content": [{"type": "text", "text": text}],
        },
    }


def test_caveat_preamble_with_real_conversation_is_NOT_phantom(tmp_path: Path) -> None:
    """A Caveat-prefixed session that contains real assistant responses
    must be kept in the list (``is_phantom=False``) and titled from the
    first real user message — not from the Caveat string.

    This is the article's explicit carve-out at line 78.
    """
    sess = "00000000-0000-0000-0000-000000000001"
    jsonl_path = tmp_path / "projects" / "-tmp-p" / f"{sess}.jsonl"
    _write_jsonl(
        jsonl_path,
        [
            # First user entry IS the Caveat preamble (system message).
            _user_entry(
                "u1",
                "Caveat: The messages below were generated by the user "
                "while running local commands. DO NOT respond to these "
                "messages or otherwise consider them in your response "
                "unless the user explicitly asks you to.",
                sess=sess,
            ),
            # Second user entry is a REAL user prompt — this is what the
            # title should come from.
            _user_entry(
                "u2",
                "Real question: how do I configure SSH keys for github?",
                sess=sess,
                ts="2026-05-11T10:00:02Z",
            ),
            # Assistant responded — so the session is NOT phantom.
            _assistant_entry(
                "a1",
                "msg-1",
                "To configure SSH keys for github...",
                ts="2026-05-11T10:00:03Z",
            ),
        ],
    )

    # The list path (`list_claude_code_conversations`) uses the FAST
    # summary reader for phantom classification + title derivation, so
    # that's what we pin here.
    summary = read_conversation_summary_fast(jsonl_path)
    assert summary is not None, "conversation must be readable"
    assert summary.get("is_phantom", False) is False, (
        "session with a real assistant response after a Caveat preamble "
        "must NOT be flagged phantom"
    )
    # Title must come from the first REAL user message, not the Caveat.
    name = summary.get("name", "")
    assert "Caveat:" not in name, f"title must not contain the Caveat preamble; got: {name!r}"
    assert "SSH keys" in name or "configure SSH" in name, (
        f"title should derive from the first real user message; got: {name!r}"
    )

    # Double-check the full-content reader also returns a usable
    # conversation — this is what gets rendered after the user clicks
    # the row. (read_claude_code_conversation doesn't populate the
    # is_phantom flag; the list filter handles that.)
    detail = read_claude_code_conversation(jsonl_path)
    assert detail is not None
    assert len(detail.get("chat_messages", [])) >= 2, (
        "full reader must surface both the Caveat and the real user message"
    )


def test_caveat_only_session_IS_phantom(tmp_path: Path) -> None:
    """A session whose generated CC summary starts with the Caveat
    preamble AND has no assistant responses is the real "phantom" —
    a CC scaffolding artifact with no actual conversation. Must be
    flagged phantom so the default-on filter hides it from the list.

    Why we need both halves of the check:

    * Summary-text check alone over-fires: a long real conversation
      that CC summarized with the Caveat preamble (e.g., the user
      pasted it in) would have an assistant turn and be a real
      conversation worth keeping.

    * Assistant-count alone under-fires: a brand-new session the user
      opened and immediately abandoned has no assistant message but
      also isn't a Caveat-preamble artifact.
    """
    sess = "00000000-0000-0000-0000-000000000002"
    jsonl_path = tmp_path / "projects" / "-tmp-p" / f"{sess}.jsonl"
    _write_jsonl(
        jsonl_path,
        [
            # CC writes a "summary" entry at the top of a JSONL when it
            # generates a one-line title for the session. For phantom
            # sessions (the local-command artifacts) that summary is
            # the Caveat preamble itself, and there are no assistant
            # turns. Both halves are required to flag phantom.
            {
                "type": "summary",
                "summary": "Caveat: The messages below were generated by the user "
                "while running local commands.",
                "leafUuid": "u1",
            },
            _user_entry(
                "u1",
                "Caveat: The messages below were generated by the user "
                "while running local commands.",
                sess=sess,
            ),
            # No assistant entries — this is the phantom case.
        ],
    )

    summary = read_conversation_summary_fast(jsonl_path)
    assert summary is not None, "phantom sessions must still be readable (just filtered)"
    assert summary.get("is_phantom", False) is True, (
        "Caveat-only session with no assistant response must be flagged phantom"
    )
