import { test, expect, makeSummary, withNetRetry } from './fixtures'

/**
 * Sidebar behavior coverage for the Medium-article claims that previously
 * had no explicit Playwright test:
 *
 *   B1 — Source filter actually filters (Claude Desktop / Claude Code).
 *   B2 — Project grouping is collapsible (CC sessions).
 *   B3 — Sidebar row shows source badge + formatted timestamp + message count.
 *   B6 — Phantom session toggle: hidden by default; toggle reveals.
 *   B7 — Caveat-with-content sessions are titled from the first non-system
 *        message (i.e., they survive the phantom filter and render with the
 *        user-meaningful title rather than getting hidden as empty).
 *
 * The actual phantom-filter logic lives in the backend; from the frontend's
 * perspective we verify (a) the toggle controls the `include_phantom` query
 * param, and (b) when the backend yields a session with a non-Caveat title
 * it renders that title verbatim.
 */

const DESKTOP_UUID = '00000000-0000-0000-0000-0000000000d1'
const CC_UUID = '00000000-0000-0000-0000-0000000000d2'
const STARRED_UUID = '00000000-0000-0000-0000-0000000000d3'
const CAVEAT_UUID = '00000000-0000-0000-0000-0000000000d4'
const PHANTOM_UUID = '00000000-0000-0000-0000-0000000000d5'

const desktop = makeSummary({
  uuid: DESKTOP_UUID,
  name: 'Desktop conversation about TLS handshakes',
  source: 'CLAUDE_AI',
  message_count: 12,
  human_message_count: 6,
  updated_at: '2026-04-15T08:30:00Z',
})

const cc = makeSummary({
  uuid: CC_UUID,
  name: 'Code session in repo',
  source: 'CLAUDE_CODE',
  message_count: 33,
  human_message_count: 17,
  project_path: '/Users/rpeck/Source/claude-desktop-message-exporter',
  project_name: 'claude-desktop-message-exporter',
  updated_at: '2026-04-20T15:45:00Z',
  organization_id: null,
  organization_name: null,
})

const ccSecondInSameProject = makeSummary({
  uuid: '00000000-0000-0000-0000-0000000000d6',
  name: 'Another session in same project',
  source: 'CLAUDE_CODE',
  message_count: 5,
  human_message_count: 2,
  project_path: '/Users/rpeck/Source/claude-desktop-message-exporter',
  project_name: 'claude-desktop-message-exporter',
  updated_at: '2026-04-22T11:00:00Z',
  organization_id: null,
  organization_name: null,
})

const starred = makeSummary({
  uuid: STARRED_UUID,
  name: 'Starred desktop conversation',
  source: 'CLAUDE_AI',
  is_starred: true,
  message_count: 8,
  human_message_count: 4,
  updated_at: '2026-04-19T09:00:00Z',
})

const caveatWithContent = makeSummary({
  uuid: CAVEAT_UUID,
  name: 'Investigating cache invalidation bug',
  source: 'CLAUDE_CODE',
  message_count: 15,
  human_message_count: 7,
  project_path: '/Users/rpeck/work/svc',
  project_name: 'svc',
  updated_at: '2026-04-21T14:00:00Z',
  organization_id: null,
  organization_name: null,
})

const phantomSession = makeSummary({
  uuid: PHANTOM_UUID,
  name: 'Caveat: The messages below were generated by the user',
  source: 'CLAUDE_CODE',
  message_count: 1,
  human_message_count: 0,
  project_path: '/Users/rpeck/work/svc',
  project_name: 'svc',
  updated_at: '2026-04-22T16:00:00Z',
  organization_id: null,
  organization_name: null,
})

test.describe('Sidebar — source filter (B1)', () => {
  test('selecting Claude Desktop drives the request with ?source=CLAUDE_AI', async ({ page, mockBackend }) => {
    const sourceParams: (string | null)[] = []
    await mockBackend({
      conversations: [desktop, cc],
      extraRoutes: async (p) => {
        // Re-route /api/conversations to capture the source param and return
        // a filtered list. We re-register here so this handler runs first.
        await p.unroute('**/api/conversations**')
        await p.route('**/api/conversations**', (route) => {
          const url = new URL(route.request().url())
          // Skip detail and tree URLs.
          if (/\/api\/conversations\/[^/?]+(\/tree)?($|\?)/.test(url.pathname)) {
            route.fulfill({ contentType: 'application/json', body: '{}' })
            return
          }
          const source = url.searchParams.get('source')
          sourceParams.push(source)
          let payload = [desktop, cc]
          if (source === 'CLAUDE_AI') payload = [desktop]
          else if (source === 'CLAUDE_CODE') payload = [cc]
          route.fulfill({ contentType: 'application/json', body: JSON.stringify(payload) })
        })
      },
    })

    await withNetRetry(page, () => page.goto('/'))
    // Both rows visible initially (no source filter).
    await expect(page.getByText(desktop.name)).toBeVisible()
    await expect(page.getByText(cc.name)).toBeVisible()

    // Switch to Claude Desktop only.
    await page.getByRole('combobox').filter({ hasText: /All Conversations|Claude Desktop|Claude Code/ }).first().click()
    await page.getByRole('option', { name: 'Claude Desktop' }).click()
    await expect(page.getByText(desktop.name)).toBeVisible()
    await expect(page.getByText(cc.name)).toHaveCount(0)

    // Switch to Claude Code only.
    await page.getByRole('combobox').filter({ hasText: 'Claude Desktop' }).first().click()
    await page.getByRole('option', { name: 'Claude Code' }).click()
    await expect(page.getByText(cc.name)).toBeVisible()
    await expect(page.getByText(desktop.name)).toHaveCount(0)

    // Verify the backend saw the right source params at least once each.
    expect(sourceParams).toContain('CLAUDE_AI')
    expect(sourceParams).toContain('CLAUDE_CODE')
  })
})

test.describe('Sidebar — project grouping is collapsible (B2)', () => {
  test('chevron click hides and re-shows the group items', async ({ page, mockBackend }) => {
    await mockBackend({
      conversations: [cc, ccSecondInSameProject],
    })
    await withNetRetry(page, () => page.goto('/'))

    // Switch source to Claude Code so the "Group by project" toggle appears.
    // CF1: the active-filter picker is now the first combobox in the sidebar,
    // so we filter by the source-filter's text content.
    await page.getByRole('combobox').filter({ hasText: /All Conversations|Claude Desktop|Claude Code/ }).first().click()
    await page.getByRole('option', { name: 'Claude Code' }).click()

    // Tick the "Group by project" checkbox by clicking its label (the
    // checkbox is nested inside a <label title="..."> with an icon, no
    // visible text). We click the label rather than the checkbox itself
    // because the icon-only label means the click target needs to fall on
    // the wrapper for the React change-handler to fire reliably.
    // (The previous .first() locator was a known flake — see
    // PLANS/2026.05.06-MANUAL-TEST-PLAN.md §13.)
    await page.locator('label[title="Group sessions by project"]').click()

    // Group header appears (project name + "(2)" count). Tighten the regex
    // to require the trailing count so the conversation cards (which also
    // include the project path in their accessible names) don't collide
    // with the group <button>.
    const groupHeader = page.getByRole('button', { name: /claude-desktop-message-exporter\s*\(2\)/ })
    await expect(groupHeader).toBeVisible()
    await expect(page.getByText(cc.name)).toBeVisible()
    await expect(page.getByText(ccSecondInSameProject.name)).toBeVisible()

    // Click chevron (the group header itself is the toggle button).
    await groupHeader.click()
    await expect(page.getByText(cc.name)).toHaveCount(0)
    await expect(page.getByText(ccSecondInSameProject.name)).toHaveCount(0)

    // Click again to expand.
    await groupHeader.click()
    await expect(page.getByText(cc.name)).toBeVisible()
    await expect(page.getByText(ccSecondInSameProject.name)).toBeVisible()
  })
})

test.describe('Sidebar — row metadata (B3)', () => {
  test('row shows model badge, formatted timestamp, and message count', async ({ page, mockBackend }) => {
    await mockBackend({
      conversations: [desktop, cc],
    })
    await withNetRetry(page, () => page.goto('/'))

    const desktopRow = page.locator('[role="button"]', { hasText: desktop.name })
    await expect(desktopRow).toBeVisible()
    // Model badge.
    await expect(desktopRow.getByText(desktop.model)).toBeVisible()
    // Message count.
    await expect(desktopRow.getByText(`${desktop.message_count} msgs`)).toBeVisible()
    // Timestamp text — formatDate produces something non-empty; assert presence
    // by matching at least one of "ago" / month abbrev / year fragment from
    // the source ISO timestamp.
    const timestampText = await desktopRow.locator('span').filter({ hasText: /\d/ }).allTextContents()
    expect(timestampText.length).toBeGreaterThan(0)

    // Source badges differ between the two rows.
    const ccRow = page.locator('[role="button"]', { hasText: cc.name })
    await expect(ccRow.locator('[title="Claude Code"]')).toBeVisible()
    await expect(desktopRow.locator('[title="Claude Desktop"]')).toBeVisible()
  })
})

test.describe('Sidebar — phantom session toggle (B6)', () => {
  test('checkbox controls the include_phantom query param', async ({ page, mockBackend }) => {
    const phantomFlags: (string | null)[] = []
    await mockBackend({
      conversations: [cc],
      extraRoutes: async (p) => {
        await p.unroute('**/api/conversations**')
        await p.route('**/api/conversations**', (route) => {
          const url = new URL(route.request().url())
          if (/\/api\/conversations\/[^/?]+(\/tree)?($|\?)/.test(url.pathname)) {
            route.fulfill({ contentType: 'application/json', body: '{}' })
            return
          }
          const includePhantom = url.searchParams.get('include_phantom')
          phantomFlags.push(includePhantom)
          // Default API behavior: phantoms hidden unless include_phantom=true.
          const payload = includePhantom === 'true' ? [cc, phantomSession] : [cc]
          route.fulfill({ contentType: 'application/json', body: JSON.stringify(payload) })
        })
      },
    })

    await withNetRetry(page, () => page.goto('/'))
    // Phantom hidden by default.
    await expect(page.getByText(cc.name)).toBeVisible()
    await expect(page.getByText(phantomSession.name)).toHaveCount(0)

    // Toggle the "Empty" checkbox.
    const emptyLabel = page.locator('label[title*="empty sessions"]')
    await emptyLabel.click()

    // Now the phantom row appears.
    await expect(page.getByText(phantomSession.name)).toBeVisible()

    // The flag transitioned from null/absent to 'true' across the two requests.
    expect(phantomFlags).toContain('true')
  })
})

test.describe('Sidebar — Caveat-with-content session retains its real title (B7)', () => {
  test('a CC session with a non-Caveat name renders that name verbatim', async ({ page, mockBackend }) => {
    await mockBackend({
      conversations: [caveatWithContent],
    })
    await withNetRetry(page, () => page.goto('/'))

    // The backend already resolved the title to the first non-system
    // message; the frontend just displays whatever name the API returned.
    // This test pins that contract: if the backend says
    // "Investigating cache invalidation bug", the sidebar shows that exact
    // string — NOT the underlying "Caveat: ..." preamble.
    await expect(page.getByText('Investigating cache invalidation bug')).toBeVisible()
    await expect(page.getByText(/^Caveat:/)).toHaveCount(0)
  })
})

test.describe('Sidebar — starred group always at top (B4 reinforcement)', () => {
  test('starred row appears above non-starred rows in flat view', async ({ page, mockBackend }) => {
    await mockBackend({
      // Order shuffled to prove the UI re-orders, not the API.
      conversations: [desktop, starred, cc],
    })
    await withNetRetry(page, () => page.goto('/'))

    // Starred section header is present.
    await expect(page.getByText('Starred', { exact: true })).toBeVisible()

    // The starred row appears before either non-starred row.
    const starredBox = await page.locator('[role="button"]', { hasText: starred.name }).first().boundingBox()
    const desktopBox = await page.locator('[role="button"]', { hasText: desktop.name }).first().boundingBox()
    expect(starredBox).toBeTruthy()
    expect(desktopBox).toBeTruthy()
    expect(starredBox!.y).toBeLessThan(desktopBox!.y)
  })
})
